name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  type-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-type-check
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: npm
      - uses: ./.github/workflows/modules/cache-dependencies
      - run: npm ci
      - run: npm run type-check

  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: npm
      - uses: ./.github/workflows/modules/cache-dependencies
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: npm
      - uses: ./.github/workflows/modules/cache-dependencies
      - run: npm ci
      - run: npm run test
